services:
  ollama-service:
    image: ollama/ollama:latest
    container_name: ollama-central-service
    ports:
      - "127.0.0.1:11434:11434"
    volumes:
      - ollama_storage:/root/.ollama
    restart: unless-stopped
    environment:
      - OLLAMA_ORIGINS=https://ollama.herman-tsago.tech,http://localhost
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_NUM_PARALLEL=1
      - OLLAMA_MAX_LOADED_MODELS=1
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 20s
      timeout: 10s
      retries: 6
      start_period: 60s
    cpus: 2.0
    mem_limit: 3896m

volumes:
  ollama_storage:
    driver: local
